### PR TITLE
Allow selection of birthdate

### PR DESCRIPTION
**Pull request by drallgood**
This PR extends the API to allow an optional selection of the birthdate used.
Certain groups (especially kids between 12 and 16) have different availabilities.

### CODE REVIEW

**Comment by internetztube** [comment]
Thanks for the PR!
Question regarding availability: Does it only affect the band of the vaccines or also the time slots?

**Comment by drallgood** [comment]
@internetztube 
based on my understanding (and that's just based on what was reported by the media the other day): Both.
Apparently, there are extra appointments for kids. Not sure it's true but that's what was reported

**Comment by internetztube** [comment]
Ok. Good to know. I will take a look at the PR tomorrow.
One last question: I guess your also expecting an implementation of this feature in the website project or are you planning to use the api endpoint in your own application?

**Comment by drallgood** [comment]
I'm working on the website as we speak.
haven't used Vue in a while.. or JS for that matter so it took me a few minutes to get used to it again.

I'm still not 100% on where to put the input (as it should be optional)

**Comment by internetztube** [comment]
Just implemented a new feature today. If we add more features, then I have to restructure the project anyway.
Leave the Vue project out of it. I will have a look at it this week.
Thanks!

**Comment by drallgood** [comment]
Works for me :)

**Comment by internetztube** [comment]
Looks great! Thank you! 🎉

**Comment by internetztube** [comment]
Also found a relatively good solution for the front-end. What do you think about it? @drallgood 
https://jaukerl-ooe.m8.at/

**Comment by drallgood** [comment]
Looking good! I like it!

**Pull request merged**
